# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default

jobs:
  - job: job1
    steps:
    - script: echo Hello, world! Job1
      displayName: 'Job1'
    - script: ping 127.0.0.1 -n 100
  
  - job: job2
    steps:
    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
        displayName: 'Job2'
    - script: ping 127.0.0.1 -n 100
